import { HelperService } from "App/Services/Utils/HelperService";

export const INITIAL_STATE = {
  searchFilters: {
    startDate: HelperService.getMonthStartAndEndDateTimestamp()[0],
    endDate: HelperService.getMonthStartAndEndDateTimestamp()[1],
    selectedDateType: "Date", //or Month,
    selectedMonth: new Date(HelperService.getCurrentTimestamp()).getMonth(),
    selectedTab: 0,
    psm__c: "",
  },
  tabsMapping: {
    "0": "Targets Achieved",
    "1": "Summary",
  },
  data: {
    siteCount: {},
    visitCount: {},
    eventsCount: {},
    orderValue: {},
    counters: {},
    dashboardSummary: {},
    dashboardBanner: {},
    dashboardTicker: {},
    primarySummary: [],
    campaign: {
      Status: "Success",
      Rejected: 0,
      PendingForApproval: 1,
      Message: "Success",
      ErrorCode: null,
      Draft: 2,
      Completed: 1,
      Approved: 7,
    },
    visitSummary: {},
    salesGeneral: [
      {
        attributes: {
          type: "Sales_Target__c",
          url:
            "/services/data/v45.0/sobjects/Sales_Target__c/a1Q0p000000hjUjEAI",
        },
        Id: "a1Q0p000000hjUjEAI",
        Name: "T-00012",
        Achievement__c: 5000,
        Achievement_Quantity__c: 79000,
        CreatedById: "0055g00000C5wwSAAR",
        Customer__c: null,
        Customer__r: null,
        Employee__c: "0055g00000C5wwSAAR",
        Employee__r: {
          attributes: {
            type: "User",
            url: "/services/data/v45.0/sobjects/User/0055g00000C5wwSAAR",
          },
          Id: "0055g00000C5wwSAAR",
          Name: "Sridhar Srinivasan",
        },
        Ach_Quantity__c: 79000,
        Ach_Value__c: 5000,
        Focused_part_no_type__c: false,
        From_Date__c: "2022-03-01",
        Part_No__c: null,
        Part_No__r: null,
        Status__c: "Active",
        Target__c: 10000,
        Target_Quantity__c: 71000,
        Target_Type__c: "General",
        To_Date__c: "2022-03-30",
      },
      {
        attributes: {
          type: "Sales_Target__c",
          url:
            "/services/data/v45.0/sobjects/Sales_Target__c/a1Q0p000000hjUtEAI",
        },
        Id: "a1Q0p000000hjUtEAI",
        Name: "T-00014",
        Achievement__c: 5000,
        Achievement_Quantity__c: 79000,
        CreatedById: "0055g00000C5wwSAAR",
        Customer__c: "0010p0000117ELZAA2",
        Customer__r: {
          attributes: {
            type: "Account",
            url: "/services/data/v45.0/sobjects/Account/0010p0000117ELZAA2",
          },
          Id: "0010p0000117ELZAA2",
          Name: "A-ONE DIESEL",
        },
        Employee__c: "0055g00000C5wwSAAR",
        Employee__r: {
          attributes: {
            type: "User",
            url: "/services/data/v45.0/sobjects/User/0055g00000C5wwSAAR",
          },
          Id: "0055g00000C5wwSAAR",
          Name: "Sridhar Srinivasan",
        },
        Ach_Quantity__c: 79000,
        Ach_Value__c: 5000,
        Focused_part_no_type__c: false,
        From_Date__c: "2022-04-01",
        Part_No__c: null,
        Part_No__r: null,
        Status__c: "Active",
        Target__c: 10000,
        Target_Quantity__c: 71000,
        Target_Type__c: "General",
        To_Date__c: "2022-04-30",
      },
      {
        attributes: {
          type: "Sales_Target__c",
          url:
            "/services/data/v45.0/sobjects/Sales_Target__c/a1Q0p000000hjUoEAI",
        },
        Id: "a1Q0p000000hjUoEAI",
        Name: "T-00013",
        Achievement__c: 5000,
        Achievement_Quantity__c: 79000,
        CreatedById: "0055g00000C5wwSAAR",
        Customer__c: null,
        Customer__r: null,
        Employee__c: "0055g00000C5wwSAAR",
        Employee__r: {
          attributes: {
            type: "User",
            url: "/services/data/v45.0/sobjects/User/0055g00000C5wwSAAR",
          },
          Id: "0055g00000C5wwSAAR",
          Name: "Sridhar Srinivasan",
        },
        Ach_Quantity__c: 79000,
        Ach_Value__c: 5000,
        Focused_part_no_type__c: false,
        From_Date__c: "2022-04-01",
        Part_No__c: "a0v0p000001PswJAAS",
        Part_No__r: {
          attributes: {
            type: "Item_Master__c",
            url:
              "/services/data/v45.0/sobjects/Item_Master__c/a0v0p000001PswJAAS",
          },
          Id: "a0v0p000001PswJAAS",
          Description__c: "BERU PLUG",
        },
        Status__c: "Active",
        Target__c: 10000,
        Target_Quantity__c: 71000,
        Target_Type__c: "General",
        To_Date__c: "2022-04-30",
      },
    ],
    salesFocus: [
      {
        attributes: {
          type: "Sales_Target__c",
          url:
            "/services/data/v45.0/sobjects/Sales_Target__c/a1Q0p000000hjUyEAI",
        },
        Id: "a1Q0p000000hjUyEAI",
        Name: "T-00015",
        Achievement__c: 5000,
        Achievement_Quantity__c: 79000,
        CreatedById: "0055g00000C5wwSAAR",
        Customer__c: null,
        Customer__r: null,
        Employee__c: "0055g00000C5wwSAAR",
        Employee__r: {
          attributes: {
            type: "User",
            url: "/services/data/v45.0/sobjects/User/0055g00000C5wwSAAR",
          },
          Id: "0055g00000C5wwSAAR",
          Name: "Sridhar Srinivasan",
        },
        Ach_Value__c: 5000,
        Ach_Quantity__c: 79000,
        Focused_part_no_type__c: false,
        From_Date__c: "2022-04-01",
        Part_No__c: "a0v0p000001PswKAAS",
        Part_No__r: {
          attributes: {
            type: "Item_Master__c",
            url:
              "/services/data/v45.0/sobjects/Item_Master__c/a0v0p000001PswKAAS",
          },
          Id: "a0v0p000001PswKAAS",
          Name: "Wood",
          Description__c: "REPAIR KIT",
        },
        Status__c: "Active",
        Target__c: 10000,
        Target_Quantity__c: 71000,
        Target_Type__c: "Focused",
        To_Date__c: "2022-04-30",
      },
    ],
  },
  loaders: {
    siteCountLoader: false,
    visitCountLoader: false,
    eventsCountLoader: false,
    orderValueLoader: false,
    countersLoader: false,
    dashboardSummaryLoader: false,
    dashboardBannerLoader: false,
    dashboardTickerLoader: false,
    primarySummaryLoader: false,
    campaignLoader: false,
    visitSummaryLoader: false,
    salesGeneralLoader: false,
    salesFocusLoader: false,
  },
};
