import { HelperService } from "App/Services/Utils/HelperService";
export const INITIAL_STATE = {
  createOnboardinglist: {},
  ASuccessfulOnboarding: {},
  createOnboardingLoading: false,
  OnboardingInfoFormValidation: {
    invalid: false,
    invalid_field: "",
    error_message: "",
  },
  updateOnboardinglist: {},
  UpdateOnboardingLoading: false,
  selectlist: {},
  selectedFilter: {
    selectedTab: 0,
  },

  selectedBeatFilter: {
    selectedTab: 0,
    competitor: "",
  },
  ImageList: {},
  UploadImageLoading: false,
  imageform: {},

  submitForApprovalLoader: false,
  forApprovalLoader: false,
  submitForApprovaRejectLoader: false,
  approvereject: {},

  getVisitAgainstOnboarding: [],
  getVisitOnboardingLoading: false,
  OnboardingVisitList: {},
  CreateAgainstVisitLoading: false,
  showmodaList: {},
  isShowmodal: false,
  lastvisitList: [],
  getLastVisitLoading: false,
  cityList: [],
  getcityListLoadiing: false,
  CampaignAttendees: [
    {
      attributes: {
        type: "Campaign_Attendees__c",
        url:
          "/services/data/v45.0/sobjects/Campaign_Attendees__c/a1O0p000000Vys1EAC",
      },
      Id: "a1O0p000000Vys1EAC",
      Name: "CA-000000002",
      Attendee_Name__c: "xyz",
      Address__c: "delhi",
      Phone__c: "964875421",
      Remarks__c: "Success",
      Campaign_Requisition__c: "a1G0p00000XtKbxEAF",
      Campaign_Requisition__r: {
        attributes: {
          type: "Campaign_Requisition__c",
          url:
            "/services/data/v45.0/sobjects/Campaign_Requisition__c/a1G0p00000XtKbxEAF",
        },
        Name: "CR-0027",
        Id: "a1G0p00000XtKbxEAF",
      },
    },
  ],
  getCampaignAttendeesLoading: false,

  TicketList: [
    {
      attributes: {
        type: "Ticket__c",
        url: "/services/data/v45.0/sobjects/Ticket__c/a070p000004slGDAAY",
      },
      Id: "a070p000004slGDAAY",
      Complaint_Open_Date__c: "2022-03-03T00:00:00.000+0000",
      Ticket_Category__c: null,
      Ticket_Type__c: "Availability of parts",
      Field_Team_Remarks__c: "Test",
      Complaint_Status__c: "Open",
      Complaint_Description__c: "Test",
      Solution_Provided__c: "test",
      Close_Date__c: "2022-03-03T00:00:00.000+0000",
    },
  ],
  fetchTicketLoading: false,
  Createticket: {},
  CreateTicketLoading: false,
  competitorList: {},
  getCompetitorSchemeLoader: false,
  createCampaignlist: {},
  createCampaignLoading: false,
  campaignRecord: [
    {
      attributes: {
        type: "Campaign_Requisition__c",
        url:
          "/services/data/v45.0/sobjects/Campaign_Requisition__c/a1G0p00000XtIQoEAN",
      },
      Id: "a1G0p00000XtIQoEAN",
      Name: "OF-0024",
      Branch_Manager_Approval_status__c: "Pending for approval",
      Branch__c: null,
      Campaign_Requisition_raised_by__c: "0050p000003R8HvAAK",
      Campaign_Requisition_raised_by__r: {
        attributes: {
          type: "User",
          url: "/services/data/v45.0/sobjects/User/0050p000003R8HvAAK",
        },
        Name: "RAM",
        Id: "0050p000003R8HvAAK",
      },
      Campaign_Status__c: "Draft",
      Approval_status__c: null,
      BTL_activity_type__c: "Van Campaign",
      Budget_Actual__c: null,
      Budget_Planned__c: null,
      Budget_allocated__c: null,
      Finance_Head_Approval_Status__c: null,
      Give_aways_required__c: "Writing pads",
      Marketing_Head_Approval_Status__c: null,
      Number_Actual__c: null,
      Number_Planned__c: null,
      Other_BTL_activity__c: null,
      Outcome_of_the_Campaign__c: "Successful",
      Overall_Status__c: "Pending for approval",
      Remarks__c: null,
      Snacks_Planned__c: null,
    },
    {
      attributes: {
        type: "Campaign_Requisition__c",
        url:
          "/services/data/v45.0/sobjects/Campaign_Requisition__c/a1G0p00000XtIQoEAN",
      },
      Id: "a1G0p00000XtIQoEAN",
      Name: "OF-0024",
      Branch_Manager_Approval_status__c: "Pending for approval",
      Branch__c: null,
      Campaign_Requisition_raised_by__c: "0050p000003R8HvAAK",
      Campaign_Requisition_raised_by__r: {
        attributes: {
          type: "User",
          url: "/services/data/v45.0/sobjects/User/0050p000003R8HvAAK",
        },
        Name: "RAM",
        Id: "0050p000003R8HvAAK",
      },
      Campaign_Status__c: "Pending for approval",
      Approval_status__c: null,
      BTL_activity_type__c: "Van Campaign",
      Budget_Actual__c: null,
      Budget_Planned__c: null,
      Budget_allocated__c: null,
      Finance_Head_Approval_Status__c: null,
      Give_aways_required__c: "Writing pads",
      Marketing_Head_Approval_Status__c: null,
      Number_Actual__c: null,
      Number_Planned__c: null,
      Other_BTL_activity__c: null,
      Outcome_of_the_Campaign__c: "Successful",
      Overall_Status__c: "Pending for approval",
      Remarks__c: null,
      Snacks_Planned__c: null,
    },
    {
      attributes: {
        type: "Campaign_Requisition__c",
        url:
          "/services/data/v45.0/sobjects/Campaign_Requisition__c/a1G0p00000XtIQoEAN",
      },
      Id: "a1G0p00000XtIQoEAN",
      Name: "OF-0024",
      Branch_Manager_Approval_status__c: "Pending for approval",
      Branch__c: null,
      Campaign_Requisition_raised_by__c: "0050p000003R8HvAAK",
      Campaign_Requisition_raised_by__r: {
        attributes: {
          type: "User",
          url: "/services/data/v45.0/sobjects/User/0050p000003R8HvAAK",
        },
        Name: "RAM",
        Id: "0050p000003R8HvAAK",
      },
      Campaign_Status__c: "Completed",
      Approval_status__c: null,
      BTL_activity_type__c: "Van Campaign",
      Budget_Actual__c: null,
      Budget_Planned__c: null,
      Budget_allocated__c: null,
      Finance_Head_Approval_Status__c: null,
      Give_aways_required__c: "Writing pads",
      Marketing_Head_Approval_Status__c: null,
      Number_Actual__c: null,
      Number_Planned__c: null,
      Other_BTL_activity__c: null,
      Outcome_of_the_Campaign__c: "Successful",
      Overall_Status__c: "Pending for approval",
      Remarks__c: null,
      Snacks_Planned__c: null,
    },
    {
      attributes: {
        type: "Campaign_Requisition__c",
        url:
          "/services/data/v45.0/sobjects/Campaign_Requisition__c/a1G0p00000XtIQoEAN",
      },
      Id: "a1G0p00000XtIQoEAN",
      Name: "OF-0024",
      Branch_Manager_Approval_status__c: "Pending for approval",
      Branch__c: null,
      Campaign_Requisition_raised_by__c: "0050p000003R8HvAAK",
      Campaign_Requisition_raised_by__r: {
        attributes: {
          type: "User",
          url: "/services/data/v45.0/sobjects/User/0050p000003R8HvAAK",
        },
        Name: "RAM",
        Id: "0050p000003R8HvAAK",
      },
      Campaign_Status__c: "Approved",
      Approval_status__c: null,
      BTL_activity_type__c: "Van Campaign",
      Budget_Actual__c: null,
      Budget_Planned__c: null,
      Budget_allocated__c: null,
      Finance_Head_Approval_Status__c: null,
      Give_aways_required__c: "Writing pads",
      Marketing_Head_Approval_Status__c: null,
      Number_Actual__c: null,
      Number_Planned__c: null,
      Other_BTL_activity__c: null,
      Outcome_of_the_Campaign__c: "Successful",
      Overall_Status__c: "Pending for approval",
      Remarks__c: null,
      Snacks_Planned__c: null,
    },
  ],
  getCampaignRecordLoading: false,

  createCompetitorSchemelist: {},
  createCompetitorSchemeLoading: false,

  createAttendeelist: {},
  createAttendeeLoading: false,

  updateCampaign: {},
  updateCampaignLoader: false,
  kycform: {},
  createKycFormLoading: false,
  CompetitorMasterlist: [],
  getCompetitorMasterLoading: false,
  updateKycLoading: false,
  createdticket: {},
};
