/**
 * The initial values for the redux state.
 */
import { HelperService } from "App/Services/Utils/HelperService";
export const INITIAL_STATE = {
  username: "", //
  password: "", //password for user
  token: "", //user token after user is logged in, indication that user is loggin or not.
  id: "", //agent id after generated.
  user_started_day: false, //has user started the day
  user_ended_day: false, //has user ended the day
  user_marked_absent: false, // has user marked absent,
  userLoginIsLoading: false,
  userLoginErrorMessage: false,
  validation: {
    invalid_number: false,
    invalid_password: false,
    invalid_area: false,
    error_message: "",
  },
  loginDetails: {},
  startDayId: [],
  recordId: "",
  startDayDate: "",
  endDayDate: "",

  area: "",
  latitude: "",
  longitude: "",
  agentAreas: [],
  agentCity: [],
  fetchAllAreasLoading: false,
  fetchAllAreasFailure: false,
  startDayTime: "",
  endDayTime: "",
  absentDayTime: "",
  absentReason: "Leave",
  leaveType: "Absent",
  userStartDayLoading: false,
  userEndDayLoading: false,
  userMarkedAbsentLoading: false,
  agentDetails: {},
  isASM: false,
  psmList: [],
  fetchAllPsmLoader: false,

  userLogoutIsLoading: false,
  monthNumber: "",
  pjpList: [],
  fetchPjpLoading: false,
  filteredPjpDisplayData: [],
  searchFilters: {
    selectedMonth: new Date(HelperService.getCurrentTimestamp()).getMonth(),
    startDate: HelperService.getCurrentTimestamp(),
    endDate: HelperService.getCurrentTimestamp(),
    selectedTab: 0,
    name: "",
    presentType: "",
  },

  beatlistadded: {},
  createPjpLoading: false,
  agentbeat: [],
  pjpSearchList: [],
  makePjpSearchListLoading: false,

  onboardingList: [
    {
      attributes: {
        type: "Account",
        url: "/services/data/v45.0/sobjects/Account/0010p000014Y7zZAAS",
      },
      Id: "0010p000014Y7zZAAS",
      Name: "Tania",
      Prospect_Type__c: "DEALER",
      Sub_Category__c: "PROSPECT- PRIMARY",
      Address__c: "Ttt",
      Area_Master__c: "a180p000000hbN9AAI",
      Address1__c: "Hahhs",
      Address2__c: "Hi nshh",
      Phone: "7777555464",
      Mobile__c: "7774445556",
      WEB_address__c: "www.fb.com",
      States__c: null,
      States__r: null,
      Branch_Code__c: "a170p000001pw4mAAA",
      Branch_Code__r: {
        attributes: {
          type: "Branch_Master__c",
          url:
            "/services/data/v45.0/sobjects/Branch_Master__c/a170p000001pw4mAAA",
        },
        Name: "4200",
        Id: "a170p000001pw4mAAA",
      },
      City_Master__c: "a1D0p000000y6f3EAA",
      City_Master__r: {
        attributes: {
          type: "City_Master__c",
          url:
            "/services/data/v45.0/sobjects/City_Master__c/a1D0p000000y6f3EAA",
        },
        Id: "a1D0p000000y6f3EAA",
        Name: "C48",
      },
      District__c: "a1C0p000000YwSiEAK",
      District__r: {
        attributes: {
          type: "District_Master__c",
          url:
            "/services/data/v45.0/sobjects/District_Master__c/a1C0p000000YwSiEAK",
        },
        Name: "GJ19",
        Id: "a1C0p000000YwSiEAK",
      },
      Branch_Manager__c: "0050p000003cZFnAAM",
      Branch_Manager__r: {
        attributes: {
          type: "User",
          url: "/services/data/v45.0/sobjects/User/0050p000003cZFnAAM",
        },
        Name: "ankita testing",
        Id: "0050p000003cZFnAAM",
      },
      Branch_Head__c: "0050p000003cZFnAAM",
      Branch_Head__r: {
        attributes: {
          type: "User",
          url: "/services/data/v45.0/sobjects/User/0050p000003cZFnAAM",
        },
        Name: "ankita testing",
        Id: "0050p000003cZFnAAM",
      },
      Branch_Accountant__c: "0050p000003Hmx2AAC",
      Branch_Accountant__r: {
        attributes: {
          type: "User",
          url: "/services/data/v45.0/sobjects/User/0050p000003Hmx2AAC",
        },
        Id: "0050p000003Hmx2AAC",
        Name: "SANJAY KUMAR",
      },
      FSO_Name__c: "0050p000003HmqgAAC",
      FSO_Name__r: {
        attributes: {
          type: "User",
          url: "/services/data/v45.0/sobjects/User/0050p000003HmqgAAC",
        },
        Id: "0050p000003HmqgAAC",
        Name: "SANDEEP KUMAR",
      },
      Email__c: "abc@gmail.com",
      PERCENTAGE_OF_LUCAS_TVS__c: 25,
      PERCENTAGE_OF_LISPART__c: 25,
      PERCENTAGE_OF_FIE_PARTS__c: 65,
      PAN_No__c: null,
      Aadhar_No__c: null,
      GST_No__c: null,
      Credit_Score__c: null,
      Location__c: {
        latitude: 29.5983239,
        longitude: 78.3418622,
      },
      Years_of_operation_in_current_location__c: null,
      Customer_Vertical__c: "2/3 Wheeler",
      Bank_Account_Number__c: null,
      Bank_Guarantee__c: null,
      Bank_Name__c: null,
      Amount__c: null,
      Trade_license_where_applicable__c: null,
      own_primesis__c: null,
      Does_he_has_own_vehicle_2WH_4WH__c: null,
      Are_you_dealing_with_other_brand__c: null,
      Volume_of_business_of_other_brand__c: null,
      Three_year_GSTIN_history__c: null,
      Disc_applicable_2_WH__c: "Ffa",
      Disc_applicable_SFL__c: "Vsv",
      Existing_Code_with_vertical_details__c: "Hhh",
      Disc_Applicable_Others__c: "Hshs",
      LTVS_Monthly_volume__c: null,
      DTVS_Monthly_volume__c: null,
      L_O_Monthly_volume__c: null,
      X2WH_Monthly_volume__c: null,
      Battery_Monthly_volume__c: null,
      Lube_Monthly_volume__c: null,
      Service_Monthly_volume__c: null,
      Others_Monthly_volume__c: null,
      Nationality_Proof_Voter_id_Aadhar__c: false,
      Overall_Status__c: "Draft",
      Identity_Proof_PAN_Driving_license__c: false,
      Address_Proof_GSTIN_EB_Latest_receipt__c: false,
      Billing_Details_name_address_details__c: false,
      Contact_Details__c: false,
      Alternate_Contact_Details__c: false,
      GST_certificate_ITR_filing_3yrs_if_not_a__c: false,
      Security_cheque__c: false,
      dealer_agreement__c: false,
      Portal_agreement__c: false,
      CreatedById: "0050p000003HmqgAAC",
      CreatedDate: "2022-04-05T09:49:47.000+0000",
    },
  ],
  getOnboardingLoading: false,
  getonboardingImage: {},
  getImageOnboardingLoading: false,

  fetchBeatPjpLoading: false,
  pjpBeatList: [],
  fetchTotalOutletLoader: false,
  totalOutlet: {},

  managerListData: [],
  managerListLoader: false,

  // selectManagerCheck:['payload'],
  selectManagerForm: {},
  BeatTotalOutlet: {},
  pjpform: {},
  submitApprovalLoader: false,
  approveRejectLocalPjpLoader: false,
  divisionlist: [],
  getDivisionLoading: false,
  branchMasterList: [],
  getBranchMasterLoading: false,
  AllPartMasterList: [],
  AllPartBulkMasterList: [],

  getAllPartMasterLoading: false,
};
